definitions:
  presenters.BucketRes:
    properties:
      capacity:
        example: 10
        type: integer
      created_at:
        example: "2000-12-31 23:59:59"
        type: string
      deleted_at:
        example: "2000-12-31 23:59:59"
        type: string
      id:
        example: 1
        type: integer
      name:
        example: A
        type: string
    type: object
  presenters.CreateBucketReq:
    properties:
      capacity:
        example: 10
        type: integer
      name:
        example: A
        type: string
    type: object
  presenters.CreateFruitReq:
    properties:
      bucket_id:
        example: 1
        type: integer
      expires_in:
        example: 1m
        type: string
      name:
        example: Orange
        type: string
      price:
        example: 1.99
        type: number
    type: object
  presenters.ErrorRes:
    properties:
      error:
        example: Not Found
        type: string
      message:
        example: fruit not found
        type: string
      messages:
        example:
        - invalid field
        - invalid value
        items:
          type: string
        type: array
    type: object
  presenters.FruitRes:
    properties:
      bucket_id:
        example: 1
        type: integer
      created_at:
        example: "2000-12-31 23:59:59"
        type: string
      deleted_at:
        example: "2000-12-31 23:59:59"
        type: string
      expires_at:
        example: 1m
        type: string
      id:
        example: 1
        type: integer
      name:
        example: Orange
        type: string
      price:
        example: 1.99
        type: number
    type: object
  presenters.HealthCheckRes:
    properties:
      status:
        allOf:
        - $ref: '#/definitions/presenters.HealthCheckStatus'
        example: down
    type: object
  presenters.HealthCheckStatus:
    enum:
    - up
    - down
    type: string
    x-enum-varnames:
    - HealthCheckStatusUp
    - HealthCheckStatusDown
info:
  contact: {}
paths:
  /healthcheck:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/presenters.HealthCheckRes'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/presenters.HealthCheckRes'
      summary: healthcheck
      tags:
      - health
  /v1/buckets:
    post:
      consumes:
      - application/json
      parameters:
      - description: Bucket
        in: body
        name: bucket
        required: true
        schema:
          $ref: '#/definitions/presenters.CreateBucketReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/presenters.BucketRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/presenters.ErrorRes'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/presenters.ErrorRes'
      summary: create bucket
      tags:
      - bucket
  /v1/fruits:
    post:
      consumes:
      - application/json
      parameters:
      - description: Fruit
        in: body
        name: fruit
        required: true
        schema:
          $ref: '#/definitions/presenters.CreateFruitReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/presenters.FruitRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/presenters.ErrorRes'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/presenters.ErrorRes'
      summary: create fruit
      tags:
      - fruit
  /v1/fruits/{fruitID}/buckets/{bucketID}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Fruit ID
        in: path
        name: fruitID
        required: true
        type: integer
      - description: Bucket ID
        in: path
        name: bucketID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/presenters.ErrorRes'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/presenters.ErrorRes'
      summary: remove fruit from bucket
      tags:
      - fruit
    post:
      consumes:
      - application/json
      parameters:
      - description: Fruit ID
        in: path
        name: fruitID
        required: true
        type: integer
      - description: Bucket ID
        in: path
        name: bucketID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/presenters.ErrorRes'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/presenters.ErrorRes'
      summary: add fruit on bucket
      tags:
      - fruit
swagger: "2.0"
